name: test

on:
  schedule:
    - cron: '0 12 * * *' # Esto se ejecuta cada día a las 7 am en Perú.

jobs:
  build:
    runs-on: ubuntu-latest # tipo de maquina

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Configurar el entorno de Python
      with:
        python-version: '3.x'

    - name: Run a script
      run: python ./app.py
